config/routes.rb
Rails.application.routes.draw do
  get 'suggetions/movie'
  get 'suggetions/estimate'
  resources :suggetions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/suggetion.rb
class Suggetion < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/suggetions_controller.rb
class SuggetionsController < ApplicationController
  before_action :set_suggetion, only: [:show, :edit, :update, :destroy]

  # GET /suggetions
  # GET /suggetions.json
  def index
    @suggetions = Suggetion.all
  end

  # GET /suggetions/1
  # GET /suggetions/1.json
  def show
  end

  # GET /suggetions/new
  def new
    @suggetion = Suggetion.new
  end

  # GET /suggetions/1/edit
  def edit
    @suggetion = Suggetion.find(params[:id])
  end

  # POST /suggetions
  # POST /suggetions.json
  def create
    @suggetion = Suggetion.new(suggetion_params)

    respond_to do |format|
      if @suggetion.save
        format.html { redirect_to @suggetion, notice: 'Suggetion was successfully created.' }
        format.json { render :show, status: :created, location: @suggetion }
      else
        format.html { render :new }
        format.json { render json: @suggetion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggetions/1
  # PATCH/PUT /suggetions/1.json
  def update
    respond_to do |format|
      if @suggetion.update(suggetion_params)
        format.html { redirect_to @suggetion, notice: 'Suggetion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggetion }
      else
        format.html { render :edit }
        format.json { render json: @suggetion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggetions/1
  # DELETE /suggetions/1.json
  def destroy
    @suggetion.destroy
    respond_to do |format|
      format.html { redirect_to suggetions_url, notice: 'Suggetion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggetion
      @suggetion = Suggetion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suggetion_params
      params.require(:suggetion).permit(:username, :customername, :moviedate, :estimatedate, :closestatus, :memo, :flag)
    end

    def movie
      @message = "Hello"
    end

    def estimate
      @message = "Hello"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/suggetions_helper.rb
module SuggetionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatsuDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/suggetions/_form.html.erb
<%= form_with(model: suggetion, local: true) do |form| %>
  <% if suggetion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suggetion.errors.count, "error") %> prohibited this suggetion from being saved:</h2>

      <ul>
      <% suggetion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :customername %>
    <%= form.text_field :customername %>
  </div>

  <div class="field">
    <%= form.label :moviedate %>
    <%= form.datetime_select :moviedate %>
  </div>

  <div class="field">
    <%= form.label :estimatedate %>
    <%= form.datetime_select :estimatedate %>
  </div>

  <div class="field">
    <%= form.label :closestatus %>
    <%= form.text_field :closestatus %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_field :memo %>
  </div>

  <div class="field">
    <%= form.label :flag %>
    <%= form.check_box :flag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/suggetions/edit.html.erb
<h1>マツダ保険デジタル提案</h1>
</br>
<h2><%= @suggetion.username %>様</h2>
    <div class="row">
        <div class="col-sm-3 text-center">
          <%= link_to suggetions_movie_path do %>
            <%= image_tag("movie.png" , size: :"150x150" , class: :"img-responsive") %>
          </br><h2>ご提案動画</h2>
          <% end %>
          <h3><%= (@suggetion.moviedate+60*60*9).strftime('%Y/%m/%d %H:%M') %></h3>
        </div>

        <div class="col-sm-1 d-flex align-items-center">
            <%= image_tag("arr.png" ,size: :"40x40" ,class: :"img-responsive") %>
        </div>

        <div class="col-sm-3 text-center">
          <%= link_to suggetions_estimate_path do %>
            <%= image_tag("estimate.png" , size: :"150x150" , class: :"img-responsive center-block") %>
            </br><h2>簡易見積り</h2>
          <% end %>
          <h3><%= (@suggetion.estimatedate+60*60*9).strftime('%Y/%m/%d %H:%M') %></h3>
        </div>

        <div class="col-sm-1 d-flex align-items-center">
            <%= image_tag("arr.png" , size: :"40x40" , class: :"img-responsive center-block") %>
        </div>

        <div class="col-sm-3 text-center">
          <%= link_to suggetions_path do %>
            <%= image_tag("procedure.png" , size: :"150x150" , class: :"img-responsive center-block") %>
          </br><h2>試算・手続き</h2>
          <% end %>
          <h3><%= (@suggetion.estimatedate+60*60*9).strftime('%Y/%m/%d %H:%M') %></h3>
        </div>
    </div>
</br>
<%= link_to '一覧に戻る', suggetions_path , class: :"btn btn-primary"%>

app/views/suggetions/estimate.html.erb
<h1>マツダ保険デジタル提案 簡易見積り</h1>
    <div class="row simple_estimate">
        <div class="col-sm-1"></div>
        <div class="col-sm-2">年齢</br>31</div>
        <div class="col-sm-2">車種</br>787B</div>
        <div class="col-sm-2">用途</br>通勤・通学</div>
        <div class="col-sm-2">等級</br>15</div>
        <div class="col-sm-2">免許の色</br>ゴールド</div>
        <div class="col-sm-1"></div>
    </div>
    <div class="row car_image">
      <div class="col-sm-6 text-center">
        <%= image_tag("movie.png" , :size => "256x256") %>
      </div>
      <div class="col-sm-6 d-flex align-items-center">
        <h3>あなたの保険料は</h3>
        </br>月々<h1>3,881円</h1>
      </div>
    </div>
</br>
<%= link_to '一覧に戻る', suggetions_path , class: :"btn btn-primary"%>

app/views/suggetions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>マツダ保険デジタル提案 ご提案状況一覧</h1>

<table class="table table-hover">
  <thead>
    <tr>
<%#
    <th colspan="2" scope="col"></th>
%>
      <th scope="col">ご提案</th>
      <th scope="col">担当名</th>
      <th scope="col">お客様名</th>
      <th scope="col">動画ご案内日</th>
      <th scope="col">お見積り日</th>
      <th scope="col">AIお見積り日</th>
      <th scope="col">メモ</th>
    </tr>
  </thead>

  <tbody>
    <% @suggetions.each do |suggetion| %>
      <tr>
        <td><%= link_to 'ご提案', edit_suggetion_path(suggetion), class: :"btn btn-primary" %></td>
<%#
     <td><%= link_to 'Show', suggetion %></td>
<%#
      <td><%= link_to 'Destroy', suggetion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= suggetion.username %></td>
        <td><%= suggetion.customername %></td>
        <td><%= (suggetion.moviedate+60*60*9).strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= (suggetion.estimatedate+60*60*9).strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= suggetion.closestatus %></td>
        <td><%= suggetion.memo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規ご提案履歴', new_suggetion_path, class: :"btn btn-primary"  %>

app/views/suggetions/movie.html.erb
<h1>マツダ保険デジタル ご提案動画</hi>
<main role="main" class="container">
  <div class="embed-responsive embed-responsive-16by9">
   <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/b-uAXFwztN8"></iframe>
  </div>
</main>
<h2>マツダ自動車保険スカイプラス</h2>
<%= link_to '一覧に戻る', suggetions_path , class: :"btn btn-primary"%>

app/views/suggetions/new.html.erb
<h1>New Suggetion</h1>

<%= render 'form', suggetion: @suggetion %>

<%= link_to 'Back', suggetions_path %>

app/views/suggetions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @suggetion.username %>
</p>

<p>
  <strong>Customername:</strong>
  <%= @suggetion.customername %>
</p>

<p>
  <strong>Moviedate:</strong>
  <%= @suggetion.moviedate %>
</p>

<p>
  <strong>Estimatedate:</strong>
  <%= @suggetion.estimatedate %>
</p>

<p>
  <strong>Closestatus:</strong>
  <%= @suggetion.closestatus %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @suggetion.memo %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @suggetion.flag %>
</p>

<%= link_to 'Edit', edit_suggetion_path(@suggetion) %> |
<%= link_to 'Back', suggetions_path %>